### ISSUE TITLE
Schedules don't work on Opera Mini

### ISSUE THREAD

**Issue by hhorak** [qark/DevConf#1]
When opening m.devconf.cz (version for smartphones) in Opera Mini 6.5.2 on Android 2.2, schedules are not displayed at all. Some problems are mentioned in support matrix for jQuery [1], but I've looked into it and it seems that rather localstorage (HTML5 feature) doesn't work properly in this browser. 

The patch bellow allows to use localstorage only in other browsers than opera and it works for me now. Please, consider applying the patch or find another solution.

[1] http://jquerymobile.com/gbs/

--- application.js.opera    2012-02-06 12:10:15.000000000 +0100
+++ application.js  2012-02-06 12:09:16.000000000 +0100
@@ -19,7 +19,7 @@ var scheduleDate = "2012-02-17";
 $("#schedulePage").live('pageshow', function(event) {
   console.log("DEVCONF: #schedulePage pageinit event");
   // try local storage first
-  if (localStorage) {
-  if (!jQuery.browser.opera && localStorage) {
   console.log("DEVCONF: loading schedule from local storage");
   schedule = JSON.parse(localStorage.getItem("schedule"));
  }

**Comment by qark** [comment]
Thanks for the report! I've used try/catch construct to make sure other browsers without localStorage works well too.

I tested the site with Opera Min 6.5.27452 on Android 4.0.3 and it seems working well. Could you verify it and re-open the ticket if it does not work?

**Comment by hhorak** [comment]
It works fine now, thanks ;)
